-- local status_ok,_  = pcall(vim.cmd, "colorscheme NeoSolarized")
-- 
-- if not status_ok then
--   vim.notify("NeoSolarized color scheme not installed. Add sainnhe/edge to your list of plugins.")
--   return
-- end
-- 
-- vim.cmd [[ set background=dark ]]
